config/routes.rb
Rails.application.routes.draw do
  get 'travel/index'

  get 'contact/index'

  get 'awards/index'

  get 'projects/index'
  get 'projects/maps'
  get 'projects/scheme'
  get 'projects/editor'
  get 'projects/bear_maps'
  get 'projects/doximity'
  get 'projects/novel'

  get 'about/index'

  get 'welcome/index'

  root 'welcome#index'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
end

app/controllers/travel_controller.rb
class TravelController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<script>
  var active = function() {
    $(".about_link").addClass('active');
  };
  active()
</script>

<div class="col-lg-3">
  <br />
  <%= image_tag 'picture_me.jpg', style: 'width: 100%;' %>
</div>

<div class="col-lg-9">
  <br />
  <p>My name is Ravi Pandya. I'm a sophomore at UC Berkeley studying Electrical Engineering and Computer Science.
  I work mostly with software right now, but I'm looking forward to learning about signal processing and much more
  regarding electronics!</p>
  <p>My past experience includes interning at Infosil, Inc. and Doximity.
  At <%= link_to 'Doximity', 'http://www.doximity.com', target: '_blank' %>, I worked extensively with web scraping and Ruby on Rails.
  I designed and automated web scrapers that would store data in a MySQL database. I then made a web application from scratch
  for viewing and searching the data using Ruby on Rails.
  At <%= link_to 'Infosil', 'http://www.infosil.com', target: '_blank' %>, I worked as an app designer for muliple Android and iOS apps with over 200,000 total downloads!
  </p>
  <p>
    I've also written a full length novel! It's a fantasy book about kids who can talk to animals and discover another
    world connected to our own. I was inspired to write this novel after reading novels like Harry Potter and Percy Jackson.
    I always found it amazing that authors could create entire worlds of their own with deep and rich histories--so I
    loved the idea of doing the same. I wrote it a few years back, but I hope to continue writing the sequel again soon.
  </p>
  <p>
    It's currently available on <%= link_to 'Amazon', 'https://www.amazon.com/Empire-Revealed-Ravi-Pandya/dp/0983441014', target: '_blank' %>
    in print and digital download.
  </p>
  <p>
    I was also very involved in <%= link_to 'FIRST Robotics', 'http://www.firstinspires.org/', target: '_blank' %> for 8 years,
    where teams of up to 10 people design, build, program and compete with robots against teams both locally and globally
    as well as focus on spreading STEM to the community. I was part of 3 different teams, all of which participated and
    won awards at international tournaments! My first team, M-Cubed, became the California state champions, and got 4th place
    for robot design at the world festival in Amsterdam! My second team, Phoenxtrix, got the 3rd place Champion's Award the
    world festival in St. Louis. My third team, the Robo Chicken Gator Flies of Papayaland, got the 2nd place Champion's
    Award at the Asia Pacific Invitational.
  </p>
</div>

app/views/awards/index.html.erb
<script>
  var active = function() {
    $(".awards_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <h1>Academic Honors</h1>
  <ul class="awards">
    <li>
      Oak Ridge High School Class of 2015 Valedictorian
      <ul>
        <li>
          Class size of 600, had the highest GPA at 4.45
        </li>
      </ul>
    </li>
    <li>
      UC Berkeley College of Engineering
      <%= link_to "Dean's Honors List", 'http://engineering.berkeley.edu/academics/undergraduate-guide/procedures-and-regulations' %>
      Fall 2015, Spring 2016
      <ul>
        <li>
          GPA in the top 10% of all engineering undergraduates at 3.9 for Fall and 3.925 for Spring
        </li>
      </ul>
    </li>
  </ul>

  <h1>Coding Competitions</h1>
  <ul class="awards">
    <li>
      Worked in a small team to solve coding problems in Java in 3 hours, competing against 30-50 teams
    </li>
    <li>
      1st Place Advanced Team <%= link_to 'HP CodeWars 2015', 'http://www.hpcodewars.org/?page=cw18' %>
    </li>
    <li>
      1st Place Advanced Team <%= link_to 'HP CodeWars 2013', 'http://www.hpcodewars.org/?page=cw16' %>
    </li>
    <li>
      Honorable Mention <%= link_to 'Stanford ProCo', 'http://proco.stanford.edu/index.html' %> 2014
    </li>
  </ul>

  <h1>Patents</h1>
  <ul class="awards">
    <li>
      8030888 B2 (Issued):
      <%= link_to 'Wireless Charging System for Cars', 'https://www.google.com/patents/US8030888' %>
      utilizing electromagnetic resonant coupling, similar solutions have been implemented in Korea and are being pursued by companies like Hevo Motors
    </li>
    <li>
      20110281252 (Filed):
      <%= link_to 'Paperless School Project', 'https://www.google.com/patents/US20110281252' %> in an effort to create entirely paperless schools using readily available tools
      such as a Pico Projector and an infrared pen paired with handwriting recognition software
    </li>
  </ul>

  <h1>Robotics</h1>
  <h3><%= link_to 'Robo Chicken Gator Flies of Papayaland (FTC)', 'https://sites.google.com/site/rcgfopl/Home' %></h3>
  <ul class="awards">
    <li>
      2nd Place Inspire (Champion’s) Award FTC Asia/Pacific Invitational in Sydney, Australia 2014
      <ul>
        <li>Based on robot performance, robot design and community outreach</li>
        <li>At an international invitational competition competing with other champion teams</li>
      </ul>
    </li>
    <li>
      1st Place PTC (Computer Aided Design/CAD) Design Award at FTC Asia/Pacific Invitational 2014
    </li>
    <li>
      Finalist Alliance at FTC Asia/Pacific Invitational 2014
    </li>
    <li>
      2nd Place Inspire Award at Wyoming Championship 2014
    </li>
    <li>
      3rd Place Inspire Award at Wyoming Championship 2015
    </li>
  </ul>

  <h3><%= link_to 'Phoenxtrix (FTC)', ''%></h3>
  <ul class="awards">
    <li>
      3rd Place Inspire (Champion's) Award FTC World Festival in St. Louis 2013
      <ul>
        <li>
          Tournament with over 120 teams, all of whom were champions in their own states and countries
        </li>
      </ul>
    </li>
    <li>
      1st Place Connect Award FTC World Festival 2013
      <ul>
        <li>
          Award for community outreach, we were recognized as the team to made the most difference in spreading awareness
          of both robotics and STEM in our community and around the world
        </li>
      </ul>
    </li>
    <li>
      1st Place Inspire Award FTC NorCal Championship 2013
    </li>
    <li>
      1st Place Alliance Captain FTC Northern Nevada Championship 2013
    </li>
    <li>
      1st Place Inspire Award FTC NorCal Championship 2012
    </li>
  </ul>

  <h3><%= link_to 'M-Cubed (FLL)', 'https://www.youtube.com/user/mcubedfll' %></h3>
  <ul class="awards">
    <li>
      <%= link_to 'Recognition on the California State Assembly Floor', 'https://www.youtube.com/watch?v=rtUZLh0cibM' %> for being the state champions
    </li>
    <li>
      4th Place Robot Design Award Open European Championship 2011
      <ul>
        <li>
          Award based on the design and implementation of the robot's hardware and software, was at an international invitational
          championship
        </li>
      </ul>
    </li>
    <li>
      5th Place Teamwork Award Open European Championship 2011
      <ul>
        <li>
          Award based on how well the team works together in front of a panel of judges in a silent activity
        </li>
      </ul>
    </li>
    <li>
      1st Place Champion's Award Northern California State Championship 2011
      <ul>
        <li>
          1st place out of over 400 teams based on robot performance, robot design, teamwork and a research project
        </li>
      </ul>
    </li>
  </ul>
</div>

app/views/contact/index.html.erb
<script>
  var active = function() {
    $(".contact_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <div class="col-md-6 col-lg-3">
    <br />
    <%= image_tag 'picture_me.jpg', style: 'width: 100%;' %>
    <p style="font-size: 1.5em;">
      Ravi Pandya
      <br />
      (916) 220-5954
      <br />
      rpandya922@berkeley.edu
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ravi Pandya</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <style>
      /* Remove the navbar's default margin-bottom and rounded borders */
      .navbar {
        margin-bottom: 0;
        border-radius: 0;
      }

      /* Add a gray background color and some padding to the footer */
      footer {
        background-color: black;
        padding: 25px;
      }

      .carousel-inner img {
        width: 100%; /* Set width to 100% */
        margin: auto;
      }

      /* Hide the carousel text when the screen is less than 600 pixels wide */
      @media (max-width: 600px) {
        .carousel-caption {
          display: none;
        }
      }
    </style>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body style="background-color:#292929">
    <div class="wrapper">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to(image_tag('image10.png'), root_path, class: 'navbar-brand') %>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li class="home_link"><%= link_to 'Home', welcome_index_path %></a></li>
              <li class="about_link"><%= link_to 'About', about_index_path %></li>
              <li class="dropdown projects_link">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  Projects
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'All Projects', projects_index_path %></li>
                  <li role="separator" class="divider"></li>
                  <li class="disabled"><%= link_to 'Internships', '#' %></li>
                  <li><%= link_to 'Doximity', projects_doximity_path %></li>
                  <li role="separator" class="divider"></li>
                  <li class="disabled"><%= link_to 'Personal', '#' %></li>
                  <li><%= link_to 'Novel', projects_novel_path %></li>
                  <li role="separator" class="divider"></li>
                  <li class="disabled"><%= link_to 'CS61A', '#' %></li>
                  <li><%= link_to 'Maps', projects_maps_path %></li>
                  <li><%= link_to 'Scheme', projects_scheme_path %></li>
                  <li role="separator" class="divider"></li>
                  <li class="disabled"><%= link_to 'CS61B', '#' %></li>
                  <li><%= link_to 'Text Editor', projects_editor_path %></li>
                  <li><%= link_to 'Bear Maps', projects_bear_maps_path %></li>
                  <li role="separator" class="divider"></li>
                  <li class="disabled"><%= link_to 'Robotics', '#' %></li>

                </ul>
              </li>
              <li class="awards_link"><%= link_to 'Awards/Honors', awards_index_path %></li>
              <li class="travel_link"><%= link_to 'Travel', travel_index_path %></li>
              <li class="contact_link"><%= link_to 'Contact', contact_index_path %></li>
            </ul>
          </div>
        </div>
      </nav>

      <div id="main-container" class="container-fluid">
        <div class="row" style="font-size: 1.25em; text-align: left; text-justify: inter-word;">
          <%= yield %>
        </div>
      </div>
      <div class="push"></div>
    </div>

    <footer class="footer">
      <div class="text-muted">
        <div style="display: block; margin-left: auto; margin-right: 0;" class="text-center">
          Made in Berkeley, CA
          <%= link_to(image_tag('linkedin-icon.png', style: 'height: 25px;'), 'http://www.linkedin.com/in/ravi-pandya', target: '_blank') %>
          <%= link_to(image_tag('facebook-icon5.png', style: 'height: 25px'), 'http://www.facebook.com/ravi.pandya.129', target: '_blank') %>
          <%= link_to(image_tag('github-icon.png', style: 'height: 25px'), 'http://www.github.com/rpandya922', target: '_blank') %>
          <div>
            (C) RAVI PANDYA 2016 ALL RIGHTS RESERVED
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/projects/bear_maps.html.erb
<script>
  var active = function() {
    $(".projects_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <br />
  <p>Code for this project can be found on my <%= link_to 'GitHub', 'http://www.github.com/rpandya922/bear-maps' %>!</p>
  <%= render 'shared/project', title: 'Bear Maps', description: $bear_maps_description, img: 'bear-maps.png' %>
</div>

app/views/projects/doximity.html.erb
<script>
  var active = function() {
    $(".projects_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <br />
  <p>Code for these projects can be found on my <%= link_to 'GitHub', 'http://www.github.com/rpandya922?tab=repositories' %>!</p>
  <h1>Doximity</h1>
  <%= render 'shared/project', title: 'Doc Jobs', description: $doc_jobs_description, img: 'doc-jobs.png' %>
  <%= render 'shared/project', title: 'Job Intel', description: $job_intel_description, img: 'job-intel.png' %>
</div>

app/views/projects/editor.html.erb
<script>
  var active = function() {
    $(".projects_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <br />
  <p>Code for this project can be found on my <%= link_to 'GitHub', 'http://www.github.com/rpandya922/text-editor' %>!</p>
  <%= render 'shared/project', title: 'Text Editor', description: $editor_description, img: 'editor-screenshot.png' %>
</div>

app/views/projects/index.html.erb
<script>
  var active = function() {
    $(".projects_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <br />
  <p>Code for my projects can be found on my <%= link_to 'GitHub', 'http://www.github.com/rpandya922?tab=repositories', target: '_blank' %>!
  Due to course policies, class projects are not included on my GitHub, however.</p>
  <h1>Doximity</h1>
  <%= render 'shared/project', title: 'Doc Jobs', description: $doc_jobs_description, img: 'doc-jobs.png' %>
  <%= render 'shared/project', title: 'Job Intel', description: $job_intel_description, img: 'job-intel.png' %>
  <h1>Personal</h1>
  <p>This book can be found on <%= link_to 'Amazon', 'https://www.amazon.com/Empire-Revealed-Ravi-Pandya/dp/0983441014', target: '_blank' %>!</p>
  <%= render 'shared/project', title: 'An Empire Revealed', description: $novel_description, img: 'novel.jpg' %>
  <h1>CS61B</h1>
  <%= render 'shared/project', title: 'Text Editor', description: $editor_description, img: 'editor-screenshot.png' %>
  <%= render 'shared/project', title: 'Bear Maps', description: $bear_maps_description, img: 'bear-maps.png' %>
  <h1>CS61A</h1>
  <%= render 'shared/project', title: 'Scheme Interpreter', description: $scheme_description, img: 'project-scheme.png' %>
  <%= render 'shared/project', title: 'Maps', description: $maps_description, img: 'project-maps.png' %>
  <br />
</div>

app/views/projects/maps.html.erb
<script>
  var active = function() {
    $(".projects_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <br />
  <p>Code for this project can be found on my <%= link_to 'GitHub', 'http://www.github.com/rpandya922/maps' %>!</p>
  <%= render 'shared/project', title: 'Maps', description: $maps_description, img: 'project-maps.png' %>
</div>

app/views/projects/novel.html.erb
<script>
  var active = function() {
    $(".projects_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <br />
  <p>This book can be found on <%= link_to 'Amazon', 'https://www.amazon.com/Empire-Revealed-Ravi-Pandya/dp/0983441014' %>!</p>
  <%= render 'shared/project', title: 'An Empire Revealed', description: $novel_description, img: 'novel.jpg' %>
</div>

app/views/projects/scheme.html.erb
<script>
  var active = function() {
    $(".projects_link").addClass('active');
  };
  active()
</script>

<div class="container-fluid">
  <br />
  <p>Code for this project can be found on my <%= link_to 'GitHub', 'http://www.github.com/rpandya922/scheme-interpreter' %>!</p>
  <%= render 'shared/project', title: 'Scheme Interpreter', description: $scheme_description, img: 'project-scheme.png' %>
</div>

app/views/shared/_project.html.erb
<div class="row">
  <div class="col-lg-4" style="text-align: left;">
    <h2>
      <%= title %>
    </h2>
    <p>
      <%= description %>
    </p>
  </div>
  <div class="col-lg-8">
    <br />
    <%= image_tag img, class: 'pull-right', style: 'width:100%;margin-bottom:10px;' %>
    <br />
  </div>
</div>

app/views/travel/index.html.erb
<script>
  var active = function() {
    $(".travel_link").addClass('active');
  };
  active()
</script>
<div class="container-fluid">
  <h3 class="text-center">More pictures coming soon!</h3>
  <div class="row">
    <br />
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= image_tag 'alaska.png', class: 'img-thumbnail welcome-image', style: 'width: 100%;' %>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= image_tag 'glacier.png', class: 'img-thumbnail welcome-image', style: 'width: 100%;' %>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= image_tag 'portland.png', class: 'img-thumbnail welcome-image', style: 'width: 100%;' %>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= image_tag 'portland-waterfall.png', class: 'img-thumbnail welcome-image', style: 'width: 100%;' %>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= image_tag 'sf.png', class: 'img-thumbnail welcome-image', style: 'width: 100%;' %>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= image_tag 'skiing.png', class: 'img-thumbnail welcome-image', style: 'width: 100%;' %>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= image_tag 'sunset.png', class: 'img-thumbnail welcome-image', style: 'width: 100%;' %>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= image_tag 'lake.png', class: 'img-thumbnail welcome-image', style: 'width: 100%;' %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<script>
  var active = function() {
    $(".home_link").addClass('active');
  };
  active()
</script>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag('computer_blurred.png') %>
      <div class="carousel-caption">
        <h3>Software</h3>
        <p>Java, Python, Ruby on Rails</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag('smash-wii-u.png') %>
      <div class="carousel-caption">
        <h3>Super Smash Bros.</h3>
        <p></p>
      </div>
    </div>

    <div class="item">
      <%= image_tag('mountains.png') %>
      <div class="carousel-caption">
        <h3>Traveling</h3>
        <p>Alaska, Amsterdam, London, Sydney</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag('robotics.png') %>
      <div class="carousel-caption">
        <h3>Robotics</h3>
        <p>FLL & FTC</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container text-center">
  <h3>What I Do</h3><br>
  <div class="row">
    <div class="col-sm-4">
      <%= link_to(image_tag('editor-screenshot.png', class: 'img-thumbnail welcome-image', style: 'width:100%;'), projects_editor_path) %>
    </div>
    <div class="col-sm-4">
      <%= link_to(image_tag('novel.jpg', class: 'img-thumbnail welcome-image', style: 'width:100%;'), projects_novel_path) %>
    </div>
    <div class="col-sm-4">
      <div style="color: black;">
        <%= link_to(button_tag('UC Berkeley Student', class: 'well btn-default', style: 'width: 100%;'), 'https://www.berkeley.edu', target: '_blank')%>
      </div>
      <div style="color: black;">
        <%= link_to(button_tag('Software Developer', class: 'well btn-default', style: 'width: 100%;'), 'https://www.github.com/rpandya922', target: '_blank')%>
      </div>
      <div style="color: black;">
        <%= link_to(button_tag('Undergraduate Researcher', class: 'well btn-default', style: 'width: 100%;'), 'http://hart.berkeley.edu/hri.html', target: '_blank')%>
      </div>
    </div>
  </div>
</div><br>